version: '3'

services:
  timescale:
    image: timescale/timescaledb:2.1.0-pg13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  tsdbperf:
    image: vincev/tsdbperf
    entrypoint:
      - /app/tsdbperf
      - --db-host
      - timescale
